package main

func main() {
	keys, _ := PGPGenerateKeyPair("Ramil", "", "ramil@example.com", "password")
	println(keys.PrivateKey)
	println(keys.PublicKey)
	pubKey, _ := PGPPublicKeyFromPrivate(keys.PrivateKey, "password")
	println(pubKey)
	newPk, _ := PGPPrivateKeyChangePassword(keys.PrivateKey, "password", "newPassword")
	println(newPk)
	cipher, _ := PGPEncrypt(keys.PublicKey, "Hello World!")
	println(cipher)
	msg, _ := PGPDecrypt(newPk, cipher, "newPassword")
	println(msg)
	aesCipher := AESEncrypt("password", "Hello World!")
	println(aesCipher)
	aesMsg, _ := AESDecrypt("password", aesCipher)
	println(aesMsg)
	salt := AESSalt(32)
	println(salt)
	hash := HashSha256([]byte("hash"))
	println(hash)
	hexHash := HashHexSha256([]byte("hash"))
	println(hexHash)
	base64enc := Base64Encode([]byte("Hello World!"))
	println(base64enc)
	base64dec, _ := Base64Decode(base64enc)
	println(base64dec)
	hexEnc := HexEncode(hash)
	println(hexEnc)
	hexDec, _ := HexDecode(hexEnc)
	println(hexDec)
}
